-- ============================================================
-- Necro Dash - Supabase Database Schema
-- ============================================================
-- Run this in your Supabase SQL Editor to set up all tables,
-- RLS policies, triggers, and functions.
-- ============================================================
